---
title: "01-explore"
output: html_document
date: "2023-02-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

theme_set(
  theme_classic() +
    theme(
      plot.background = element_rect(fill = "transparent", colour = NA),
      panel.background = element_rect(fill = "transparent", colour = NA)
    )
)
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text(color = "black", family="Avenir"),
    plot.title = element_text(size = 18,colour = "black", hjust = 0.5),
    plot.subtitle=element_text(face="italic", hjust = 0.5),
    plot.caption=element_text(size = 7, hjust = 0.5),
    axis.ticks = element_blank(),
    panel.background = element_blank(), 
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "white", fill=NA, size=2)
  )
}
```

```{r}
library(sf)
library(tidyverse)
library(here)
library(janitor)
library(tidytuesdayR)

cats_uk <- read_csv("https://www.datarepository.movebank.org/bitstream/handle/10255/move.883/Pet%20Cats%20United%20Kingdom.csv?sequence=3") |> 
  clean_names() |> 
  # Standardize things and reorder columns.
  select(
    tag_id = tag_local_identifier,
    event_id:location_lat,
    ground_speed,
    height_above_ellipsoid,
    algorithm_marked_outlier,
    manually_marked_outlier,
    study_name
  ) |> 
  # Explicitly encode FALSE in the outlier columns.
  tidyr::replace_na(
    list(
      algorithm_marked_outlier = FALSE,
      manually_marked_outlier = FALSE
    )
  )

cats_uk_reference <- read_csv("https://www.datarepository.movebank.org/bitstream/handle/10255/move.884/Pet%20Cats%20United%20Kingdom-reference-data.csv?sequence=1") |>
  clean_names() |> 
  mutate(
    # animal_life_stage is ALMOST just age in years.
    age_years = case_when(
      str_detect(animal_life_stage, fixed("<")) ~ 0L,
      str_detect(animal_life_stage, "year") ~ str_extract(
        animal_life_stage, "\\d+"
      ) |> 
        as.integer(),
      TRUE ~ NA_integer_
    )
  ) |> 
  # There are only a handful of unique values for the comments, extract those.
  separate_wider_delim(
    animal_comments,
    "; ",
    names = c("hunt", "prey_p_month")
  ) |> 
  mutate(
    hunt = case_when(
      str_detect(hunt, "Yes") ~ TRUE,
      str_detect(hunt, "No") ~ FALSE,
      TRUE ~ NA
    ),
    prey_p_month = as.numeric(
      str_remove(prey_p_month, "prey_p_month: ")
    )
  ) |> 
  # manipulation_comments similarly has a pattern.
  separate_wider_delim(
    manipulation_comments,
    "; ",
    names = c("hrs_indoors", "n_cats", "food")
  ) |> 
  mutate(
    hrs_indoors = as.numeric(
      str_remove(hrs_indoors, "hrs_indoors: ")
    ),
    n_cats = as.integer(
      str_remove(n_cats, "n_cats: ")
    )
  ) |> 
  separate_wider_delim(
    food,
    ",",
    names = c("food_dry", "food_wet", "food_other")
  ) |> 
  mutate(
    food_dry = case_when(
      str_detect(food_dry, "Yes") ~ TRUE,
      str_detect(food_dry, "No") ~ FALSE,
      TRUE ~ NA
    ),
    food_wet = case_when(
      str_detect(food_wet, "Yes") ~ TRUE,
      str_detect(food_wet, "No") ~ FALSE,
      TRUE ~ NA
    ),
    food_other = case_when(
      str_detect(food_other, "Yes") ~ TRUE,
      str_detect(food_other, "No") ~ FALSE,
      TRUE ~ NA
    )
  ) |>
  # Drop uninteresting fields.
  select(
    -animal_life_stage,
    -attachment_type,
    -data_processing_software,
    -deployment_end_type,
    -duty_cycle,
    -deployment_id,
    -manipulation_type,
    -tag_manufacturer_name,
    -tag_mass,
    -tag_model,
    -tag_readout_method
  )

glimpse(cats_uk)
glimpse(cats_uk_reference)

# cats_uk |> write_csv(
#   here(
#     "data",
#     "2023",
#     "2023-01-31",
#     "cats_uk.csv"
#   )
# )

# cats_uk_reference |> write_csv(
#   here(
#     "data",
#     "2023",
#     "2023-01-31",
#     "cats_uk_reference.csv"
#   )
# )
```


```{r}

```

speed by age
animal_sex
prey_p_month
hrs_indoors


animal_taxon "Felis catus"

```{r}
max_speeds <- cats_uk |> 
    filter(!manually_marked_outlier, !algorithm_marked_outlier) |> 
  filter(ground_speed > 10000) |> 
  group_by(tag_id) |> 
  summarise(max_speed = max(ground_speed), .groups = "drop")




dat <- cats_uk_reference |> 
  select(tag_id, hrs_indoors, hunt, prey_p_month, animal_sex, age_years) |> 
  left_join(max_speeds)

dat |> 
  count(hunt, animal_sex)



dat |> 
  ggplot() +
  aes(x = prey_p_month) + 
  geom_density() +
  facet_wrap(~ animal_sex)

dat |> 
  ggplot() +
  aes(y = prey_p_month, x = age_years, color = prey_p_month) + 
  geom_count() + 
  geom_smooth() + 
  scale_color_viridis_c()
  
dat |> 
  ggplot() +
  aes(x = hrs_indoors) + 
  geom_bar() +
  facet_wrap(~ animal_sex)


dat |> 
  count(hunt, animal_sex)

dat |> 
  ggplot() +
  aes(y = max_speed, x = age_years, color = animal_sex) +
  geom_point() +
  geom_smooth(fill = "grey90") +
  rcartocolor::scale_color_carto_d()

```



```{r}

dat |> 
  ggplot() +
  aes(y = prey_p_month, x = max_speed, color = animal_sex) +
  geom_point() +
  geom_smooth(fill = "grey90") +
  rcartocolor::scale_color_carto_d()
```


```{r}
cats_uk_sf <- cats_uk |> 
  left_join(cats_uk_reference) |> 
  st_as_sf(coords = c("location_long", "location_lat"), 
           crs = 4326)
  
```

```{r}
uk <- map_data(map = "world", region = "UK")

# stcrop 
# Bounding box:  xmin: -5.758854 ymin: 50.10352 xmax: -4.208614 ymax: 50.88222

ggplot(uk) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "gray80", color = "gray50") +
  geom_sf(data = cats_uk_sf, shape = 21, size = 3) +
  aes(fill = ground_speed) +
  mapTheme()

```

